// mentors types

export const SEARCH_MENTORS = "SEARCH_MENTORS";
export const SEARCH_MENTOR = "SEARCH_MENTOR";
export const CLEAR_MENTORS = "CLEAR_MENTORS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_ERROR = "SEARCH_MENTOR";
export const REQUEST = "REQUEST";
//@user login
export const MENTOR_USER_LOGIN_SUCCESS = "MENTOR_USER_LOGIN_SUCCESS";
export const MENTOR_USER_LOGIN_FAIL = "MENTOR_USER_LOGIN_FAIL";
export const MENTOR_USER_LOGOUT = "MENTOR_USER_LOGIN_LOGOUT";
export const MENTOR_USER_LOGOUT_FAIL = "MENTOR_USER_LOGOUT_FAIL";


// @MENTOR_user register
export const MENTOR_USER_REGISTER_SUCCESS = "MENTOR_USER_REGISTER_SUCCESS";
export const MENTOR_USER_REGISTER_FAIL = "MENTOR_USER_REGISTER_FAIL";

// @MENTOR_user profile

export const MENTOR_USER_PROFILE_SUCCESS = "MENTOR_USER_PROFILE_SUCCESS";
export const MENTOR_USER_PROFILE_FAIL = "MENTOR_USER_PROFILE_FAIL";

