// mentors types

export const SEARCH_MENTORS = "SEARCH_MENTORS";
export const SEARCH_MENTOR = "SEARCH_MENTOR";
export const CLEAR_MENTORS = "CLEAR_MENTORS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_ERROR = "SEARCH_MENTOR";
export const REQUEST = "REQUEST";
//@user login
export const MENTEE_USER_LOGIN_SUCCESS = "MENTEE_USER_LOGIN_SUCCESS";
export const MENTEE_USER_LOGIN_FAIL = "MENTEE_USER_LOGIN_FAIL";
export const MENTEE_USER_LOGOUT = "MENTEE_USER_LOGIN_LOGOUT";
export const MENTEE_USER_LOGOUT_FAIL = "MENTEE_USER_LOGOUT_FAIL";

// @MENTEE_user register
export const MENTEE_USER_REGISTER_SUCCESS = "MENTEE_USER_REGISTER_SUCCESS";
export const MENTEE_USER_REGISTER_FAIL = "MENTEE_USER_REGISTER_FAIL";

// @MENTEE_user profile

export const MENTEE_USER_PROFILE_SUCCESS = "MENTEE_USER_PROFILE_SUCCESS";
export const MENTEE_USER_PROFILE_FAIL = "MENTEE_USER_PROFILE_FAIL";
